In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
# prompt: gpu is available or not

import torch
if torch.cuda.is_available():
    print("GPU is available")
    print(torch.cuda.get_device_name(0))
    print(torch.cuda.device_count())
else:
    print("GPU is not available")


GPU is available
Tesla T4
1


Using Empty

In [2]:

x = torch.empty(5, 3) # creates an empty tensor with 5 rows and 3 columns It allocates memory for the tensor but does not initialize the values — the values inside x are whatever random garbage values were already in that memory location.
x


tensor([[4.9262e+34, 4.4875e-41, 4.9262e+34],
        [4.4875e-41, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 1.1631e-43],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [3]:
# prompt: check type

print(type(x))


<class 'torch.Tensor'>


In [6]:


# Using zeors

x = torch.zeros(5, 3) # creates a tensor with 5 rows and 3 columns filled with zeros
x


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# prompt: using one

# Using ones
x = torch.ones(5, 3, dtype=torch.float16) # creates a tensor with 5 rows and 3 columns filled with ones
x


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [10]:
# prompt: using random

import torch
import random

# Example using random
random_tensor = torch.rand(2, 2)  # Creates a 2x2 tensor with random numbers between 0 and 1
print("\nRandom Tensor:")
print(random_tensor)

# Example with a specific random seed (for reproducibility) This will generate a random tensor, but it will always be the same every time you run it with seed 42.
torch.manual_seed(42)  # Set the seed
random_tensor_seeded = torch.rand(2,2)
print("\nRandom Tensor with seed 42:")
print(random_tensor_seeded)

# Another random tensor with the same seed will be the same
torch.manual_seed(42)
another_random_tensor_seeded = torch.rand(2,2)
print("\nAnother Random Tensor with seed 42:")
another_random_tensor_seeded



Random Tensor:
tensor([[0.0072, 0.0390],
        [0.9929, 0.9131]])

Random Tensor with seed 42:
tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

Another Random Tensor with seed 42:


tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

In [14]:
#creating own tensor
torch.tensor([[1,2,3],[6,7,8]])

tensor([[1, 2, 3],
        [6, 7, 8]])

In [16]:
print("using arrange ->", torch.arange(0,10,2))

using arrange -> tensor([0, 2, 4, 6, 8])


In [17]:
#starting from 0 to 10 , 5 numbers with each having same gaps
print("using linspace ->", torch.linspace(0,10,5))

using linspace -> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [20]:
#identity matrix
print(torch.eye(5))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [21]:
print(torch.full((2,3), 5))

tensor([[5, 5, 5],
        [5, 5, 5]])


Tensor Shape

In [31]:
a=torch.tensor([[1,2,3],[6,7,8]])
a.shape


torch.int64

In [25]:
torch.empty_like(a)

tensor([[       433791696896, 7310593858020254331, 3616445622929465956],
        [6068655667612233013, 3689356515585177904, 6501000145162940974]])

In [27]:
torch.zeros_like(a)


tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.ones_like(a)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [34]:
#changing data type
a.to(torch.float32)

tensor([[1., 2., 3.],
        [6., 7., 8.]])

In [36]:
torch.rand_like(a, dtype=torch.float32)

tensor([[0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332]])

In [37]:
#to find memory location
id(a)

137539495120336

In [38]:
id(x)

137539647612464

In [41]:
#to copy data item in different memory location
b=a.clone()
id(b)

137538992951984

In [42]:
b

tensor([[1, 2, 3],
        [6, 7, 8]])

Tensor operation on GPU

In [43]:
torch.cuda.is_available()

True

In [44]:
#to perform operations in gpu's RAM (VRAM)
device = torch.device('cuda')

In [45]:
torch.rand((2,3), device=device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [46]:

r= torch.rand(2,3)
r

tensor([[0.9346, 0.5936, 0.8694],
        [0.5677, 0.7411, 0.4294]])

In [48]:
#moving existing tensor to gpu
t=r.to(device)
t

tensor([[0.9346, 0.5936, 0.8694],
        [0.5677, 0.7411, 0.4294]], device='cuda:0')

In [3]:
c= torch.rand(4,4)
c

tensor([[0.4412, 0.1885, 0.5894, 0.3353],
        [0.7525, 0.2573, 0.8732, 0.2362],
        [0.5137, 0.3095, 0.2881, 0.7432],
        [0.9528, 0.4883, 0.8232, 0.1076]])

In [4]:
c.reshape(2,2,2,2)

tensor([[[[0.4412, 0.1885],
          [0.5894, 0.3353]],

         [[0.7525, 0.2573],
          [0.8732, 0.2362]]],


        [[[0.5137, 0.3095],
          [0.2881, 0.7432]],

         [[0.9528, 0.4883],
          [0.8232, 0.1076]]]])

In [5]:
c.flatten()

tensor([0.4412, 0.1885, 0.5894, 0.3353, 0.7525, 0.2573, 0.8732, 0.2362, 0.5137,
        0.3095, 0.2881, 0.7432, 0.9528, 0.4883, 0.8232, 0.1076])

In [7]:
d=torch.rand(2,3,4)
d

tensor([[[0.8524, 0.5586, 0.3461, 0.4373],
         [0.0980, 0.8085, 0.1809, 0.9034],
         [0.4245, 0.7855, 0.0732, 0.7667]],

        [[0.3834, 0.8042, 0.6070, 0.3164],
         [0.3434, 0.7636, 0.4266, 0.9636],
         [0.3246, 0.9334, 0.6777, 0.7748]]])

In [8]:
#from above the position 0=2,3=1,4=2,  now we can change the positons by:
e=d.permute(2,1,0)
e

tensor([[[0.8524, 0.3834],
         [0.0980, 0.3434],
         [0.4245, 0.3246]],

        [[0.5586, 0.8042],
         [0.8085, 0.7636],
         [0.7855, 0.9334]],

        [[0.3461, 0.6070],
         [0.1809, 0.4266],
         [0.0732, 0.6777]],

        [[0.4373, 0.3164],
         [0.9034, 0.9636],
         [0.7667, 0.7748]]])

In [9]:
#unsqueeze
#image sixe
#used for adding dimension in desired position
i= torch.rand(226,226,3)
i.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [13]:
j= torch.rand(1,20)
j.squeeze(0).shape

torch.Size([20])

converting numpy and pytorch


In [14]:
import numpy as np

In [15]:
n=torch.tensor([1,2,3])
n

tensor([1, 2, 3])

In [16]:
m=n.numpy()
m

array([1, 2, 3])

In [17]:
s=np.array([1,2,3])
s

array([1, 2, 3])

In [18]:
torch.from_numpy(s)

tensor([1, 2, 3])